### PR TITLE
Various improvements, fixes

### PR DESCRIPTION
**Pull request by CountCulture**

### CODE REVIEW

**Comment by CountCulture** [comment]
Francis: Think this is working this time. Not sure if I have visibility to see it it cleanly merges. If there are conflicts, let me know.

**Comment by frabcus** [comment]
The only conflict was the version number!

Now also on RubyGems https://rubygems.org/gems/scraperwiki

**Comment by CountCulture** [comment]
Great. Did you bump the version number?

**Comment by frabcus** [comment]
Yes!

**Pull request merged**
