### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by CountCulture**
- Save_var, get_var should cope with non-string values (convert to/from JSON)
- Allow block to be passed to #select
- Allow default table name to be set in config

### CODE REVIEW

**Comment by frabcus** [comment]
Does this replace https://github.com/scraperwiki/scraperwiki-ruby/pull/21 ?

**Comment by frabcus** [comment]
Also it won't automatically merge...

**Comment by CountCulture** [comment]
Sorry. I meant to do a pull request on our fork. I'll do that first, then do a clean pull request on the main repo here.

**Comment by frabcus** [comment]
Ah OK!

And thank you :)

Also, say in the pull request if you'd value a new release on Ruby
Gems...

Francis

**Pull request closed without merging**
